name: Send Discord Message
on: [workflow_dispatch]

jobs:
  send-message:
    runs-on: ubuntu-latest
    steps:
      - name: Send Webhook
        uses: liondadev/discord-action@v2.1.3
        with:
          webhook-url: ${{ secrets.WEBHOOK_URL }}
          message: My Message
