name: Status Check Functions
on: [push]

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Sleep
        run: sleep 20
      - name: fail
        id: failstep
        run: exit 1
      - name: runs on failure for step 2
        if: failure() && steps.failstep.conclusion == 'failure'
        run: echo 'Runs on failure'
      - name: runs on failure for any
        if: failure()
        run: echo 'Runs on failure for any'
      - name: runs on success
        # this is the default behavior
        if: success()
        run: echo 'Runs on success'
      - name: always runs
        if: always()
        run: echo 'Always Runs'
      - name: runs when cancelled
        if: cancelled()
        run: echo 'Runs on cancelled'
  job-2:
    runs-on: ubuntu-latest
    needs: job-1
    if: failure()
    steps:
      - run: echo 'job 2'
