name: Using reuseable workflors
on:
  workflow_dispatch:
    inputs:
      name:
        description: Input Description
        type: string
        default: "Lion"
        required: false

jobs:
  calling-a-reuseable-workflow:
    uses: liondadev/workflows/.github/workflows/reuseable.yml@main
    with:
      name: ${{ inputs.name }}
    secrets:
      access-token: ${{ secrets.ACCESS_TOKEN }}
