name: Using reuseable workflors
on:
  workflow_dispatch:
    inputs:
      name:
        description: Input Description
        type: string
        default: "Lion"
        required: false

jobs:
  calling-a-reuseable-workflow:
    uses: liondadev/workflows/.github/workflows/reuseable.yml@main
    with:
      name: ${{ inputs.name }}
    secrets:
      access-token: ${{ secrets.ACCESS_TOKEN }}
  calling-from-same-wf:
    uses: ./.github/workflows/reuseable.yml
  using-the-output:
    runs-on: ubuntu-latest
    needs: calling-from-same-wf
    steps:
      - run: echo ${{ needs.calling-from-same-wf.outputs.date }}
